title: "Sakshi Pandey"
description: "RTL Design and Verification Enthausiast| AI/ML Lead at MLSA DGI| Keen Researcher | "
theme: jekyll-theme-minimal

# Social Links
github_username: sakshipandey04
linkedin: https://www.linkedin.com/in/sakshi-pandey-86a87b257
email: pandeysakshi9315@gmail.com

# Build Settings
markdown: kramdown
